[package]
name = "tapioca"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.0"
enotation = { git = "https://github.com/dannypsnl/enotation.git" }

[dev-dependencies]
insta = "1.42.0"
